### ISSUE TITLE
bluetooth file transfer does not work

### ISSUE THREAD

**Issue by steadfasterX** [xdajog/android_i927_sediROM#12]
# Version

v2.0.63
# Description

Transfering files via bluetooth stops working in v2.0 / v1.7?

**Comment by organic2** [comment]
I test it soon againg. But im remember i dont have problem with 1.7

**Comment by steadfasterX** [comment]
confirmed by http://forum.xda-developers.com/showpost.php?p=63691028&postcount=9

**Comment by organic2** [comment]
I test it. I no have bt file transfer on sedirom v 2.0.63 with sedikernel v1

**Comment by organic2** [comment]
My mean is no have bt transfer problem with sedirom v 2.0.63 beta with sedi kernel v1
One "problem" word miss on last post, sorry

**Comment by steadfasterX** [comment]
no problem and you can edit (small pencil at the right site) your posts ;)
I have fixed that bug in my unreleased code already
